# Generated by Django 6.0.2 on 2026-03-18 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='expéditeur',
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lue'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messagerie.message', verbose_name='Message associé'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
