# Generated by Django 6.0.2 on 2026-03-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementEncadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('periode_essai', models.BooleanField(default=False)),
                ('payé', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEncadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('SUSPENSION', 'Suspension'), ('BANNISSEMENT', 'Bannissement')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_sanction', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('COMPORTEMENT', 'Comportement inapproprié'), ('ABSENCE', 'Absence non justifiée'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('traité', models.BooleanField(default=False)),
            ],
        ),
    ]
