# Generated by Django 6.0.2 on 2026-03-06 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementencadreur',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.encadreur'),
        ),
        migrations.AddField(
            model_name='documentencadreur',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.encadreur'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.encadreur'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_reçus', to='utilisateurs.encadreur'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL),
        ),
    ]
