# Generated by Django 6.0.2 on 2026-03-18 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
        ('utilisateurs', '0003_encadreur_bio_encadreur_date_inscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentencadreur',
            options={'ordering': ['-date_upload']},
        ),
        migrations.AlterModelOptions(
            name='sanction',
            options={'ordering': ['-date_sanction']},
        ),
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-date_signalement']},
        ),
        migrations.AddField(
            model_name='documentencadreur',
            name='commentaire_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentencadreur',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanction',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='commentaire_traitement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentencadreur',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_admin', to='utilisateurs.encadreur'),
        ),
        migrations.AlterField(
            model_name='documentencadreur',
            name='fichier',
            field=models.FileField(upload_to='documents/encadreurs/'),
        ),
        migrations.AlterField(
            model_name='documentencadreur',
            name='type_document',
            field=models.CharField(choices=[('DIPLOME', 'Diplôme'), ('CNI', "Carte Nationale d'Identité"), ('CV', 'Curriculum Vitae'), ('CERTIFICAT', 'Certificat'), ('AUTRE', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='utilisateurs.encadreur'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='type_sanction',
            field=models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('SUSPENSION_1J', 'Suspension 1 jour'), ('SUSPENSION_7J', 'Suspension 7 jours'), ('SUSPENSION_30J', 'Suspension 30 jours'), ('BANNISSEMENT', 'Bannissement définitif')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to='utilisateurs.encadreur'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='type_signalement',
            field=models.CharField(choices=[('COMPORTEMENT', 'Comportement inapproprié'), ('ABSENCE', 'Absence non justifiée'), ('RETARD', 'Retard répété'), ('FACTURATION', 'Problème de facturation'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentencadreur',
            unique_together={('encadreur', 'type_document')},
        ),
        migrations.DeleteModel(
            name='AbonnementEncadreur',
        ),
    ]
