# Generated by Django 6.0.2 on 2026-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_documentencadreur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentencadreur',
            options={'ordering': ['-date_upload'], 'verbose_name': 'Document encadreur', 'verbose_name_plural': 'Documents encadreurs'},
        ),
        migrations.AlterModelOptions(
            name='sanction',
            options={'ordering': ['-date_sanction'], 'verbose_name': 'Sanction', 'verbose_name_plural': 'Sanctions'},
        ),
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-date_signalement'], 'verbose_name': 'Signalement', 'verbose_name_plural': 'Signalements'},
        ),
        migrations.RenameField(
            model_name='signalement',
            old_name='traité',
            new_name='traite',
        ),
        migrations.AlterField(
            model_name='documentencadreur',
            name='type_document',
            field=models.CharField(choices=[('DIPLOME', 'Diplome'), ('CNI', "Carte Nationale d'Identite"), ('CV', 'Curriculum Vitae'), ('CERTIFICAT', 'Certificat'), ('AUTRE', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='type_sanction',
            field=models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('SUSPENSION_1J', 'Suspension 1 jour'), ('SUSPENSION_7J', 'Suspension 7 jours'), ('SUSPENSION_30J', 'Suspension 30 jours'), ('BANNISSEMENT', 'Bannissement definitif')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='type_signalement',
            field=models.CharField(choices=[('COMPORTEMENT', 'Comportement inapproprie'), ('ABSENCE', 'Absence non justifiee'), ('RETARD', 'Retard repete'), ('FACTURATION', 'Probleme de facturation'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
