# Generated by Django 6.0.2 on 2026-03-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avis', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to='utilisateurs.apprenant'),
        ),
        migrations.AddField(
            model_name='avis',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to='utilisateurs.encadreur'),
        ),
    ]
