# Generated by Django 6.0.2 on 2026-03-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
