# Generated by Django 6.0.2 on 2026-03-18 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0003_avis_date_modification_avis_reponse'),
        ('utilisateurs', '0003_encadreur_bio_encadreur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('apprenant', 'encadreur')},
        ),
    ]
