# Generated by Django 6.0.2 on 2026-03-09 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadreur',
            name='diplome_principal',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='disponibilites',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='localisation',
        ),
        migrations.AddField(
            model_name='apprenant',
            name='niveau_scolaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='type_apprenant',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('ELEVE', 'Élève autonome')], default='ELEVE', max_length=20),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], default='HOMME', max_length=10),
        ),
        migrations.AddField(
            model_name='enfant',
            name='prenom',
            field=models.CharField(default='Prénom', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='matieres',
            field=models.CharField(default='Non spécifié', max_length=255),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='niveaux',
            field=models.CharField(default='Tous niveaux', max_length=255),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='niveau_scolaire',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='nom',
            field=models.CharField(default='Nom', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('APPRENANT', 'Apprenant'), ('ENCADREUR', 'Encadreur'), ('ADMIN', 'Administrateur')], default='APPRENANT', max_length=20),
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CNI', 'Carte Nationale d’Identité'), ('DIPLOME', 'Diplôme'), ('CV', 'Curriculum Vitae'), ('PHOTO', 'Photo')], default='CNI', max_length=50)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentVerification',
        ),
    ]
