# Generated by Django 6.0.2 on 2026-03-18 03:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_remove_encadreur_diplome_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadreur',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='nb_evaluations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='commentaire_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprenant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadreur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
