# Generated by Django 6.0.2 on 2026-03-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_encadreur_bio_encadreur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apprenant',
            options={'verbose_name': 'Apprenant', 'verbose_name_plural': 'Apprenants'},
        ),
        migrations.AlterModelOptions(
            name='encadreur',
            options={'verbose_name': 'Encadreur', 'verbose_name_plural': 'Encadreurs'},
        ),
        migrations.AlterModelOptions(
            name='enfant',
            options={'verbose_name': 'Enfant', 'verbose_name_plural': 'Enfants'},
        ),
        migrations.AlterModelOptions(
            name='verificationdocument',
            options={'verbose_name': 'Document de vérification', 'verbose_name_plural': 'Documents de vérification'},
        ),
    ]
