# Generated by Django 6.0.2 on 2026-03-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_apprenant_options_alter_encadreur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadreur',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='description',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='matieres',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='niveaux',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='tarif',
        ),
        migrations.AddField(
            model_name='encadreur',
            name='presentation',
            field=models.TextField(blank=True, verbose_name='Présentation'),
        ),
    ]
