# Generated by Django 6.0.2 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_remove_encadreur_bio_remove_encadreur_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadreur',
            name='rayon_km',
            field=models.PositiveIntegerField(default=0, help_text='Rayon de déplacement (km)'),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='se_deplace',
            field=models.BooleanField(default=False, help_text='Accepte de se déplacer'),
        ),
    ]
