# Generated by Django 6.0.2 on 2026-03-26 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_encadreur_rayon_km_encadreur_se_deplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apprenant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='encadreur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enfant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificationdocument',
            options={},
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='presentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='rayon_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='se_deplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='niveau_scolaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', '8 chiffres requis')]),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='type_document',
            field=models.CharField(choices=[('CNI', 'CNI'), ('DIPLOME', 'Diplôme'), ('CV', 'CV'), ('PHOTO', 'Photo')], max_length=20),
        ),
    ]
