# Generated by Django 6.0.2 on 2026-03-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_delete_specialisation'),
        ('utilisateurs', '0007_alter_apprenant_options_alter_encadreur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif', models.IntegerField(verbose_name='Tarif par heure (FCFA)')),
                ('type_cours', models.CharField(choices=[('DOMICILE', 'À domicile'), ('GROUPE', 'Cours groupés')], default='DOMICILE', max_length=20)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.classe')),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='utilisateurs.encadreur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.matiere')),
            ],
        ),
    ]
