# Generated by Django 6.0.2 on 2026-03-18 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
        ('utilisateurs', '0003_encadreur_bio_encadreur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localisation',
            options={'ordering': ['ville', 'quartier'], 'verbose_name': 'Localisation', 'verbose_name_plural': 'Localisations'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['nom'], 'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['code'], 'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AlterModelOptions(
            name='specialisation',
            options={'ordering': ['encadreur', 'matiere'], 'verbose_name': 'Spécialisation', 'verbose_name_plural': 'Spécialisations'},
        ),
        migrations.AlterField(
            model_name='serie',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code (ex: C, D, A)'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='utilisateurs.encadreur'),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='catalogue.localisation'),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='catalogue.matiere'),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='catalogue.niveau'),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialisations', to='catalogue.serie'),
        ),
        migrations.AlterUniqueTogether(
            name='localisation',
            unique_together={('ville', 'quartier')},
        ),
        migrations.AlterUniqueTogether(
            name='serie',
            unique_together={('niveau', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='specialisation',
            unique_together={('encadreur', 'matiere', 'niveau', 'localisation')},
        ),
    ]
