# Generated by Django 6.0.2 on 2026-03-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_localisation_options_alter_matiere_options_and_more'),
        ('utilisateurs', '0004_alter_apprenant_options_alter_encadreur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisation',
            name='rayon_km',
            field=models.PositiveIntegerField(default=0, help_text='Rayon de déplacement (km)'),
        ),
        migrations.AddField(
            model_name='specialisation',
            name='se_deplace',
            field=models.BooleanField(default=False, help_text='Accepte de se déplacer'),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='catalogue.niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'ordre'],
                'unique_together': {('niveau', 'nom')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='specialisation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specialisation',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Classe spécifique (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='catalogue.classe'),
        ),
        migrations.AlterUniqueTogether(
            name='specialisation',
            unique_together={('encadreur', 'matiere', 'classe', 'localisation')},
        ),
    ]
