# Generated by Django 6.0.2 on 2026-03-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_specialisation_rayon_km_specialisation_se_deplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisation',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarif horaire pour cette combinaison', max_digits=8),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Classe spécifique', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='catalogue.classe'),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='catalogue.niveau'),
        ),
    ]
