# Generated by Django 6.0.2 on 2026-03-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_specialisation_tarif_alter_specialisation_classe_and_more'),
        ('cours', '0004_remove_demandecours_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialisation',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='specialisation',
            name='niveau',
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='classe',
            field=models.ForeignKey(default=1, help_text='Classe précise (ex: 6ème, Terminale A, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='catalogue.classe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarif horaire (FCFA)', max_digits=8),
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
