# Generated by Django 6.0.2 on 2026-03-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_specialisation_serie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialisation',
        ),
    ]
