# Generated by Django 6.0.2 on 2026-03-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiement', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.encadreur'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.encadreur'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiement.transaction'),
        ),
    ]
