# Generated by Django 6.0.2 on 2026-03-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilites', models.TextField(blank=True, help_text="Jours/heures proposés par l'apprenant", null=True)),
                ('localite', models.CharField(blank=True, help_text='Adresse si cours à domicile', max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_proposee', models.DateTimeField(blank=True, null=True)),
                ('duree_proposee', models.PositiveIntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('lieu_cours', models.CharField(blank=True, help_text="Lieu fixé par l'encadreur (cours groupé)", max_length=255, null=True)),
                ('tarif_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PROPOSITION', 'Proposition encadreur'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
