# Generated by Django 6.0.2 on 2026-03-18 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_localisation_options_alter_matiere_options_and_more'),
        ('cours', '0002_initial'),
        ('utilisateurs', '0003_encadreur_bio_encadreur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandecours',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Demande de cours', 'verbose_name_plural': 'Demandes de cours'},
        ),
        migrations.AlterField(
            model_name='demandecours',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_emises', to='utilisateurs.apprenant'),
        ),
        migrations.AlterField(
            model_name='demandecours',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='utilisateurs.encadreur'),
        ),
        migrations.AlterField(
            model_name='demandecours',
            name='enfant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='utilisateurs.enfant'),
        ),
        migrations.AlterField(
            model_name='demandecours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='catalogue.matiere'),
        ),
        migrations.AlterField(
            model_name='demandecours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='catalogue.niveau'),
        ),
        migrations.AlterField(
            model_name='demandecours',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='catalogue.serie'),
        ),
    ]
