# Generated by Django 6.0.2 on 2026-03-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_demandecours_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecours',
            name='serie',
        ),
    ]
